### PR TITLE
fix rss address for mehdihadeli's blog

### PR DESCRIPTION
**Pull request by mehdihadeli**

### CODE REVIEW

**Comment by matthiasjost** [comment]
I cannot merge a PR here since the file is generated automatically.
However if you want to manually correct the RSS feed you can do so in the dotnet-content-creators repository by adding it like this

```
[Blog RSS](https://....)

```

**Comment by mehdihadeli** [comment]
Where do you get the RSS path?

**Comment by matthiasjost** [comment]
> Where do you get the RSS path?

I parse the URL with the label Blog for each creator. I then look into link and href tags to get the feed.

**Comment by mehdihadeli** [comment]
> I cannot merge a PR here since the file is generated automatically. However if you want to manually correct the RSS feed you can do so in the dotnet-content-creators repository by adding it like this
> 
> ```
> [Blog RSS](https://....)
> ```

I have a Blog section out there, should I add new section also for RSS?

**Pull request closed without merging**
